version: "{branch}-ci-{build}"
os: Visual Studio 2019

branches:
  only:
    - master

init:
  - cmd: dir
#  - cmd: dir c:\Qt\5.15.2\mingw81_32\bin\
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set APPVEYOR_PATH=%PATH%
  - echo %APPVEYOR_FOLDER%

install:
  - cmd: appveyor DownloadFile https://cran.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe -FileName rtools40-x86_64.exe
  - cmd: rtools40-x86_64.exe /SILENT
  - cmd: C:\rtools40\usr\bin\pacman --needed --noconfirm -Sy
  - cmd: C:\rtools40\usr\bin\pacman --noconfirm -S  mingw-w64-{i686,x86_64}-xz
  - cmd: C:\rtools40\usr\bin\pacman --noconfirm -S  mingw-w64-{i686,x86_64}-expat
  - cmd: C:\rtools40\usr\bin\pacman --noconfirm -S  mingw-w64-{i686,x86_64}-make
  - cmd: C:\rtools40\usr\bin\pacman --noconfirm -S  mingw-w64-{i686,x86_64}-openssl
  - cmd: C:\rtools40\usr\bin\pacman --noconfirm -S  mingw-w64-{i686,x86_64}-curl
  - cmd: C:\rtools40\usr\bin\pacman --noconfirm -S  mingw-w64-{i686,x86_64}-boost
  - cmd: appveyor DownloadFile https://cran.r-project.org/bin/windows/base/R-4.1.2-win.exe -FileName R-4.1.2-win.exe
  - cmd: R-4.1.2-win.exe /SILENT /DIR="c:\R" 
  - cmd: cd c:\projects
  - cmd: git clone https://github.com/vle-forge/vle.git



before_build:
# build and install vle
  - cmd: cd c:\projects\vle
  - cmd: mkdir buildvle-rvle-x64
  - cmd: mkdir buildvle-rvle-i386
  - cmd: cd buildvle-rvle-x64
  - cmd: set PATH=C:\rtools40\mingw64\bin;C:\R\bin\x64;%ProgramFiles%\CMake\bin
  - cmd: cmake.exe -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DBOOST_INCLUDEDIR=c:\rtools40\mingw64\include -DWITH_CVLE=OFF -DWITH_DOXYGEN=OFF -DWITH_GVLE=OFF -DCMAKE_INSTALL_PREFIX=c:/rvle-bin/64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - cmd: mingw32-make -j2
  - cmd: mingw32-make install
  - cmd: cd ..\buildvle-rvle-i386 
  - cmd: set PATH=C:\rtools40\mingw32\bin;C:\R\bin\x32;%ProgramFiles%\CMake\bin
  - cmd: cmake.exe -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DBOOST_INCLUDEDIR=c:\rtools40\mingw32\include -DWITH_CVLE=OFF -DWITH_DOXYGEN=OFF -DWITH_GVLE=OFF -DCMAKE_INSTALL_PREFIX=c:/rvle-bin/32 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - cmd: mingw32-make -j2
  - cmd: mingw32-make install
  - cmd: cd ..\.. 


build_script:
  - cmd: dir C:\rtools40\usr\bin
  - cmd: set PATH=C:\R\bin\;C:\rtools40\usr\bin
  - cmd: set MINGW_PATH=c:/rtools40
  - cmd: set VLE_PATH=c:/rvle-bin
  - cmd: cd c:\projects
  - cmd: R --vanilla -e install.packages('RUnit',repos='https://cloud.r-project.org')
  - cmd: R CMD build rvle
  - cmd: R CMD INSTALL --build  rvle
  - cmd: dir .
  - cmd: MOVE rvle_2.1.0-0.zip rvle
artifacts:
  - path: rvle_2.1.0-0.zip
    name: app


#  - cmd: set PATH=%QtDirTools%\bin;%QtDir%\bin;%CMakePath%\bin;%OLD_PATH%
#  - cmd: mkdir %BuildPath%
#  - cmd: cd %BuildPath%
#  - cmd: echo %PATH%
#  - cmd: cmake.exe -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=%VleDeps% -DBOOST_INCLUDEDIR=%MingwPath%\include -DWITH_MVLE=OFF -DWITH_CVLE=OFF -DWITH_DOXYGEN=OFF -DWITH_GVLE=ON -# DCMAKE_INSTALL_PREFIX=%InstallPath% -DCMAKE_BUILD_TYPE=RelWithDebInfo %SourcePath%
#  - cmd: mingw32-make VERBOSE=1 -j4
#  - cmd: mingw32-make install

after_build:
#  - cmd: set PATH=%InnoSetupPath%;%OLD_PATH%
#  - cmd: cd %SourcePath%\share
#  - cmd: echo %PATH%
#  - cmd: iscc.exe vle.iss
#  - cmd: set PATH=%APPVEYOR_PATH%
#  - cmd: 7z a vle.zip Output\*.exe

#artifacts:
#  - path: share\vle.zip
#    name: app
